### ISSUE TITLE
"Empty Dataframe" and "Index: [ ]" when writing from namd data to lammps

### ISSUE THREAD

**Issue by Bernardo-A-Roque** [compMathUPRH/granules#2]
No estoy seguro del formato que use lammps, pero me parece que "Empty Dataframe" no es la manera correcta. Digo lo mismo sobre el Index.

Una vez entienda como simular con lammps revisaré esto y veré como corregirlo

**Comment by compSciUPRH** [comment]
Empty Dataframe lo produce Granules en el archivo de topologia cuando no tiene datos para esa sección.
