### ISSUE TITLE
Demasiados archivos .pyc, __pycche__ y otraa basura

### ISSUE THREAD

**Issue by compSciUPRH** [compMathUPRH/granules#5]
Hacer Makefiles en todos los directorios que tengan una cláusula "clean" que se debe ejecutar antes de hacer cualquier commit.

**Comment by Bernardo-A-Roque** [comment]
añadí un gitignore que incluye todos los __pycache__ y los archivos .pyc

Si falta algo, hay que añadirlo al .gitignore
