### ISSUE TITLE
LammpsData object has some broken methods

### ISSUE THREAD

**Issue by Bernardo-A-Roque** [compMathUPRH/granules#6]
Usé grep para ver que las siguientes lineas no funcionarán luego de haber hecho la reorganización:

> grep -n "self.atoms" ./package/granules/structure/LAMMPSdata.py                                                                   

121:        self.atoms       = AtomsDF()
129:        self.atoms.setFromPSF(charmm)
130:        self.velocities.setToZero(self.atoms)
131:        self.masses.setFromPSF(charmm.psf.atoms,self.atoms)
232:        atomIds = atomIds.set_index('aID_x').join(self.atoms[['aID', 'Q']].set_index('aID'))
234:        atomIds = atomIds.join(self.atoms[['aID', 'aType']].set_index('aID')).reset_index(drop=True)
236:        atomIds = atomIds.set_index('aID_y').join(self.atoms[['aID', 'Q']].set_index('aID'))
237:        atomIds = atomIds.join(self.atoms[['aID', 'aType']].set_index('aID')).reset_index(drop=True)
276:                self.atoms.set_index('aID')
280:                self.atoms.set_index('aID')
301:                self.atoms.set_index('aID')
305:                self.atoms.set_index('aID')
309:                self.atoms.set_index('aID')
335:                self.atoms.set_index('aID')
339:                self.atoms.set_index('aID')
343:                self.atoms.set_index('aID')
347:                self.atoms.set_index('aID')
1407:        #cfile.write(self.atoms.to_string(index=False, columns=self.atoms.columns, header=False))

> grep -n "self.bonds" ./package/granules/structure/LAMMPSdata.py                                                                   

138:        self.bonds       = BondsDF()
147:        self.bonds.setFromPSF(charmm)
275:        bi = self.bonds.set_index('Atom1').join(
279:        bj = self.bonds.set_index('Atom2').join(
286:        coeffs = self.bonds[['bID','bType']].set_index('bType').join(
1319:        self.bondCoeffs.setFromPSF(charmm, self.bonds)

**Comment by LemuelRivera** [comment]
Cambios al llamar self.atom y otros, se areglo un error de llamada encontrado en el metodo read de la clase LammpsData.
